Mappeinnlevering 2/EatInOsloMVC/Models/EatInOsloContext.cs
using Microsoft.EntityFrameworkCore;

namespace EatInOsloMVC.Models{

    public class EatInOsloContext:DbContext{
        public EatInOsloContext(DbContextOptions<EatInOsloContext> options):base(options){}

        public DbSet<Restaurant> Restaurant {get; set;}

        public DbSet<Review> Review {get; set;}
    }
}

Mappeinnlevering 2/EatInOsloMVC/Models/Restaurants.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace EatInOsloMVC.Models{

    public class Restaurant{
        [Key]
        public int ID { get; set; }

        public string RestaurantName{ get; set; }
        
        [ForeignKey("RestaurantID")]

        public ICollection<Review> Review { get; set; }
    }
}

//en annmeldelse kan kun ha en 
//restaurant, men en restaurant 
//kan ha flere annmeldelser

Mappeinnlevering 2/EatInOsloMVC/Models/Reviews.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace EatInOsloMVC.Models{

    public class Review{
        [Key]
        public int ID { get; set; }

        public string AuthorName { get; set; }

        public string Title{ get; set; }

        public string ReviewText { get; set; }

        [ForeignKey("RestaurantID")]
        public int? RestaurantID {get; set;}
        public Restaurant Restaurant {get; set;}
       
    }
}

Mappeinnlevering 2/EatInOsloMVC/Controllers/UserController.cs
using Microsoft.AspNetCore.Mvc;

namespace EatInOsloMVC.Controllers{
    public class UserRestaurant:Controller{
        public IActionResult Welcome(){
            return View();
        }

        public IActionResult ShowReviews(){
            return View();
        }

        public IActionResult WriteReview(){
            return View();
        }
    }
}

Mappeinnlevering 2/EatInOsloMVC/Controllers/UserRestaurantController.cs
using Microsoft.AspNetCore.Mvc;
using EatInOsloMVC.Models;
using System.Collections.Generic;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;

namespace EatInOsloMVC.Controllers{
    public class UserRestaurantController:Controller{

        private readonly EatInOsloContext _context;

        public UserRestaurantController(EatInOsloContext context){
            _context = context;
        }
        public IActionResult WriteReviews(){
            return View();
        }   

         [HttpPost]
        public async Task<IActionResult> WriteReviews([Bind("ID, AuthorName, Title, ReviewText, Restaurant, RestaurantID")]Review review){
            if(ModelState.IsValid){
                _context.Review.Add(review);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(ShowRestaurants));
            }else{
                return View(review);
            }
        }

        public async Task<IActionResult> ShowRestaurants(){
            List<Restaurant> restaurantList = await _context.Restaurant.ToListAsync();
            return View(restaurantList);
        }

    [HttpGet]
        public async Task<IActionResult> ShowReviews(int? id){
            Restaurant list = await _context.Restaurant.Include("Review").SingleOrDefaultAsync(_restaurant => _restaurant.ID == id);
            return View(list);
        }

    }
}

Mappeinnlevering 2/EatInOsloMVC/Views/AdminRestaurant/AddRestaurants.cshtml
@model Restaurant


<section>

    <section class="add-form">
        <h3>Add Restaurant</h3>
        <form asp-action="AddRestaurants">
        <label>Restaurant name
                <input class="input-box" asp-for="RestaurantName" type="text">
            </label>
            
            <input type="submit" value="Add restaurant">
        </form>
    </section>

Mappeinnlevering 2/EatInOsloMVC/Views/AdminRestaurant/AdminPage.cshtml
<section>
    <h1 id="admin-navbar">Admin navbar</h1>
    <nav id="navbar">
                <a asp-controller="AdminRestaurant" asp-action="AdminPage">All Restaurants</a>       
                <a asp-controller="AdminRestaurant" asp-action="AllReviews">All Reviews</a>
                <a asp-controller="AdminRestaurant" asp-action="AddRestaurants">Add Restaurant</a>
                
        </nav>

    <div id="admin-message">
        <h1>Hei admin</h1>
        <p>Denne siden viser alle Restauranter som er på nettsiden.</p>
        <p>På adminmenyen kan du velge hva du ønsker å gjøre.</p>
    </div>

    <section>
    @{
        foreach (Restaurant restaurant in Model)
        {
            <article class="restaurant-article">
                   
                <h3>@restaurant.RestaurantName</h3>
                <a class="admin-buttons" asp-controller="AdminRestaurant" asp-action="EditRestaurants" asp-route-id="@restaurant.ID">Edit Restaurant</a>
                <a class="admin-buttons"  asp-controller="AdminRestaurant" asp-action="DeleteRestaurants" asp-route-id="@restaurant.ID">Delete Restaurant</a>

        </article>
        }
    }
</section>
</section>

Mappeinnlevering 2/EatInOsloMVC/Views/AdminRestaurant/AllReviews.cshtml
<section>
    <h1 id="admin-navbar">Admin navbar</h1>
    <nav id="navbar">
                <a asp-controller="AdminRestaurant" asp-action="AdminPage">All Restaurants</a>       
                <a asp-controller="AdminRestaurant" asp-action="AllReviews">All Reviews</a>
                <a asp-controller="AdminRestaurant" asp-action="AddRestaurants">Add Restaurant</a>
                
        </nav>
    <section>
    @{
        foreach (Review review in Model)
        {
            <article class="review-article">
                   <h2>@review.Title</h2>
                   <h4>@review.AuthorName mener:</h4>
                   <p>@review.ReviewText</p>
                   <hr>
                   <p>Belongs to Restaurant: @review.RestaurantID</p>
                   <a class="admin-buttons" asp-controller="AdminRestaurant" asp-action="EditReviews" asp-route-id="@review.ID">Edit Review</a>
                   <a class="admin-buttons" asp-controller="AdminRestaurant" asp-action="DeleteReviews" asp-route-id="@review.ID">Delete Review</a>
            </article>
        }
    }
</section>
</section>

Mappeinnlevering 2/EatInOsloMVC/Views/AdminRestaurant/DeleteRestaurants.cshtml
@model Restaurant

<section>

    <header>
        <h3>Delete restaurant</h3>
    </header>

    <h1 class="delete-warning">Are you sure you want to delete @Html.DisplayFor(restaurant => restaurant.RestaurantName) ?</h1>
    <section>
            <h4>ID: @Html.DisplayFor(restaurant => restaurant.ID)</h4>
            <h4>Name: @Html.DisplayFor(restaurant => restaurant.RestaurantName)</h4>
            <form asp-action="DeleteRestaurants">
                <input asp-for="ID" type="hidden">
                <input type="submit" value="Delete restaurant">
            </form>
    </section>


</section>

Mappeinnlevering 2/EatInOsloMVC/Views/AdminRestaurant/DeleteReviews.cshtml
@model Review

<section>

    <header>
        <h3>Delete review</h3>
    </header>

    <h1 class="delete-warning">Are you sure you want to delete this review?</h1>
    <section>
            <h4>ID: @Html.DisplayFor(review => review.Title)</h4>
            <h4>Name: @Html.DisplayFor(review => review.AuthorName)</h4>
            <h4>Review text: @Html.DisplayFor(review => review.ReviewText)</h4>
            <form asp-action="DeleteReviews">
                <input asp-for="ID" type="hidden">
                <input type="submit" value="Delete review">
            </form>
    </section>


</section>

Mappeinnlevering 2/EatInOsloMVC/Views/AdminRestaurant/EditRestaurants.cshtml
@model Restaurant

<section>

    <section class="add-form">
        <form asp-action="EditRestaurants">
            <h3>Edit restaurant</h3>
            <input asp-for="ID" type="hidden">
            <label>Name
                <input class="input-box" asp-for="RestaurantName" type="text">
            </label>
            <input type="submit" value="Edit restaurant">

        </form>

    </section>


</section

Mappeinnlevering 2/EatInOsloMVC/Views/AdminRestaurant/EditReviews.cshtml
@model Review


<section>

    <section class="add-form">
        <h3>Edit review</h3>
        <form asp-action="EditReviews">
            <label>Restaurant name
            <select class="input-box" id="restaurant-picker" asp-for="RestaurantID">
            <option label="Mirabel">1</option>
            <option label="Casa Mia">2</option>
            <option label="Fuser bar & for">3</option>
            <option label="Fratelli">4</option>
            <option label="Egons">5</option>
            <option label="Jekyll & Hyde">6</option>
            <option label="Chi">7</option>
            <option label="Solheimshagan">8</option>
            <option label="Bighorn Steakhose">9</option>
            <option label="Hinoki">10</option>
            </select>
            </label>
            <br>
        <label>Author name
                <input class="input-box" asp-for="AuthorName" type="text">
            </label>
            <br>
            <label>Title
                <input class="input-box" asp-for="Title" type="text">
            </label>
            <br>
            <label>Review text
                <textarea class="input-box" asp-for="ReviewText" rows="8" cols="40"></textarea>
            </label>
            <input type="submit" value="Save review">
        </form>
    </section>

Mappeinnlevering 2/EatInOsloMVC/Views/Shared/_MainLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" type="text/css" href="@Url.Content("~/css/main-style.css")">
    <title>EatInOslo</title>

</head>
<body>
    <div>
        <header id="header">
            
            <a id="logo" asp-controller="UserRestaurant" 
                asp-action="ShowRestaurants">EatInOslo</a>
        </header>

        <nav id="navbar">
                 <a asp-controller="UserRestaurant" 
                asp-action="ShowRestaurants">Vis alle restauranter</a>        
                <a asp-controller="UserRestaurant" asp-action="WriteReviews">Skriv en annmeldelse</a>
                <a asp-controller="AdminRestaurant" asp-action="AdminPage">Admin page</a>
        </nav>
        
        <main>
            @RenderBody()
        </main>

        <footer>
            <p id="footer">EatInOslo &copy; 2018</p>
        </footer>
    </div>


</body>
</html>

Mappeinnlevering 2/EatInOsloMVC/Views/UserRestaurant/ShowRestaurants.cshtml
    <section>
        <header>
            <h2>All restaurants in Lillestrøm</h2>
        </header>

        <section>
            @{
                foreach (Restaurant restaurant in Model)
                {
                    <article class="restaurant-article">
                   
                   <h3>@restaurant.RestaurantName</h3>
                   <a class="admin-buttons" asp-controller="UserRestaurant" 
                   asp-action="ShowReviews" 
                   asp-route-id="@restaurant.ID">Read Review</a>

                   </article>

                }
            }
        </section>




    </section>

Mappeinnlevering 2/EatInOsloMVC/Views/UserRestaurant/ShowReviews.cshtml
@model Restaurant
<section>
    <header>
        <h3>Reviews for</h3>
        <h1 id="restaurant-title">@Model.RestaurantName</h1>
    </header>

    
        <section>
            @foreach (Review review in Model.Review)
            {
                <article class="review-article">
                   <h2>@review.Title</h2>
                   <h4>@review.AuthorName mener:</h4>
                   <p>@review.ReviewText</p>
                </article>
                }

        </section>
    </section>
</section>

Mappeinnlevering 2/EatInOsloMVC/Views/UserRestaurant/WriteReviews.cshtml
@model Review


<section>

    <section class="add-form">
        <h3>Write review</h3>
        <form asp-action="WriteReviews">
            <label>Restaurant name
            <select class="input-box" id="restaurant-picker" asp-for="RestaurantID">
                <option label="Mirabel">1</option>
                <option label="Casa Mia">2</option>
                <option label="Fuser bar & for">3</option>
                <option label="Fratelli">4</option>
                <option label="Egons">5</option>
                <option label="Jekyll & Hyde">6</option>
                <option label="Chi">7</option>
                <option label="Solheimshagan">8</option>
                <option label="Bighorn Steakhose">9</option>
                <option label="Hinoki">10</option>
            </select>
            <br>
            </label>
        <label>Author name
                <input class="input-box" asp-for="AuthorName" type="text">
            </label>
            <br>
            <label>Title
                <input class="input-box" asp-for="Title" type="text">
            </label>
            <br>
            <label>Review text
               <textarea class="input-box" asp-for="ReviewText" rows="8" cols="40"></textarea>
            </label>
            <input type="submit" value="Save review">
        </form>
    </section>